In [21]:
#how has the average time taken to report changed over time? 
#(general)

pd.DataFrame(round(hate_crimes.groupby('year').hours_to_report.mean().loc[2019:2023],2))

      hours_to_report
year
2019           345.03
2020           116.68
2021            84.50
2022           130.46
2023           201.61